%YAML 1.2
# SPDX-FileCopyrightText: NVIDIA CORPORATION & AFFILIATES
# Copyright (c) 2022-2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
---
name: global
components:
- name: adapter_video_buffer
  type: nvidia::isaac::tensor_ops::ImageAdapter
  parameters:
    message_type: "VideoBuffer"
- name: adapter_bgr_u8
  type: nvidia::isaac::tensor_ops::ImageAdapter
  parameters:
    message_type: "Tensor"
    image_type: "BGR_U8"
- name: adapter_rgb_u8
  type: nvidia::isaac::tensor_ops::ImageAdapter
  parameters:
    message_type: "Tensor"
    image_type: "RGB_U8"
- name: adapter_bgr_f32
  type: nvidia::isaac::tensor_ops::ImageAdapter
  parameters:
    message_type: "Tensor"
    image_type: "BGR_F32"
- name: adapter_rgb_f32
  type: nvidia::isaac::tensor_ops::ImageAdapter
  parameters:
    message_type: "Tensor"
    image_type: "RGB_F32"
- name: adapter_planar_bgr_f32
  type: nvidia::isaac::tensor_ops::ImageAdapter
  parameters:
    message_type: "Tensor"
    image_type: "PLANAR_BGR_F32"
- name: adapter_planar_rgb_f32
  type: nvidia::isaac::tensor_ops::ImageAdapter
  parameters:
    message_type: "Tensor"
    image_type: "PLANAR_RGB_F32"
---
name: broadcaster
components:
- type: nvidia::gxf::Broadcast
  parameters:
    source: data_receiver
- name: data_receiver
  type: nvidia::gxf::DoubleBufferReceiver
  parameters:
    capacity: 1
- type: nvidia::gxf::MessageAvailableSchedulingTerm
  parameters:
    receiver: data_receiver
    min_size: 1
- name: data_transmitter_resizer
  type: nvidia::gxf::DoubleBufferTransmitter
  parameters:
    capacity: 1
- type: nvidia::gxf::DownstreamReceptiveSchedulingTerm
  parameters:
    transmitter: data_transmitter_resizer
    min_size: 1
---
name: resizer
components:
- name: data_receiver
  type: nvidia::gxf::DoubleBufferReceiver
  parameters:
    capacity: 12
- type: nvidia::gxf::MessageAvailableSchedulingTerm
  parameters:
    receiver: data_receiver
    min_size: 1
- name: data_transmitter
  type: nvidia::gxf::DoubleBufferTransmitter
  parameters:
    capacity: 12
- type: nvidia::gxf::DownstreamReceptiveSchedulingTerm
  parameters:
    transmitter: data_transmitter
    min_size: 1
- name: allocator
  type: nvidia::gxf::BlockMemoryPool
  parameters:
    storage_type: 1
    block_size: 1566720
    num_blocks: 40
- name: resize_operator
  type: nvidia::isaac::tensor_ops::Resize
  parameters:
    output_width: 0
    output_height: 0
    interp_type: "linear"
    border_type: "zero"
    keep_aspect_ratio: true
    receiver: data_receiver
    transmitter: data_transmitter
    pool: allocator
    input_adapter: global/adapter_video_buffer
    output_adapter: global/adapter_video_buffer
    output_name: "image"
---
name: bbox
components:
- name: data_transmitter
  type: nvidia::gxf::DoubleBufferTransmitter
  parameters:
      capacity: 12
- type: nvidia::gxf::DownstreamReceptiveSchedulingTerm
  parameters:
    transmitter: data_transmitter
    min_size: 1
- name: allocator
  type: nvidia::gxf::BlockMemoryPool
  parameters:
    storage_type: 0
    block_size: 32
    num_blocks: 40
- type: nvidia::isaac::tensor_ops::BBoxGenerator
  parameters:
    image_width: 0
    image_height: 0
    bbox_width: 0
    bbox_height: 0
    bbox_loc_x: 0
    bbox_loc_y: 0
    bbox_count: 1
    pool: allocator
    transmitter: data_transmitter
---
name: crop_and_resizer
components:
- name: data_receiver
  type: nvidia::gxf::DoubleBufferReceiver
  parameters:
    capacity: 12
- type: nvidia::gxf::MessageAvailableSchedulingTerm
  parameters:
    receiver: data_receiver
    min_size: 1
- name: bbox_receiver
  type: nvidia::gxf::DoubleBufferReceiver
  parameters:
    capacity: 12
- type: nvidia::gxf::MessageAvailableSchedulingTerm
  parameters:
    receiver: bbox_receiver
    min_size: 1
- name: data_transmitter
  type: nvidia::gxf::DoubleBufferTransmitter
  parameters:
    capacity: 12
- type: nvidia::gxf::DownstreamReceptiveSchedulingTerm
  parameters:
    transmitter: data_transmitter
    min_size: 1
- name: allocator
  type: nvidia::gxf::BlockMemoryPool
  parameters:
    storage_type: 1
    block_size: 1566720
    num_blocks: 40
- name: crop_and_resize_operator
  type: nvidia::isaac::tensor_ops::CropAndResize
  parameters:
    output_width: 0
    output_height: 0
    interp_type: "linear"
    keep_aspect_ratio: true
    receiver: data_receiver
    receiver_bbox: bbox_receiver
    transmitter: data_transmitter
    pool: allocator
    input_adapter: global/adapter_video_buffer
    output_adapter: global/adapter_video_buffer
    output_name: "image"
---
name: color_space_converter
components:
- name: data_receiver
  type: nvidia::gxf::DoubleBufferReceiver
  parameters:
    capacity: 12
- type: nvidia::gxf::MessageAvailableSchedulingTerm
  parameters:
    receiver: data_receiver
    min_size: 1
- name: data_transmitter
  type: nvidia::gxf::DoubleBufferTransmitter
  parameters:
    capacity: 12
- type: nvidia::gxf::DownstreamReceptiveSchedulingTerm
  parameters:
    transmitter: data_transmitter
    min_size: 1
- name: allocator
  type: nvidia::gxf::BlockMemoryPool
  parameters:
    storage_type: 1
    block_size: 1566720
    num_blocks: 40
- name: color_converter_operator
  type: nvidia::isaac::tensor_ops::ConvertColorFormat
  parameters:
    output_type: "RGB_U8"
    receiver: data_receiver
    transmitter: data_transmitter
    pool: allocator
    input_adapter: global/adapter_video_buffer
    output_adapter: global/adapter_video_buffer
    output_name: "image"
---
name: normalizer
components:
- name: data_receiver
  type: nvidia::gxf::DoubleBufferReceiver
  parameters:
    capacity: 12
- type: nvidia::gxf::MessageAvailableSchedulingTerm
  parameters:
    receiver: data_receiver
    min_size: 1
- name: data_transmitter
  type: nvidia::gxf::DoubleBufferTransmitter
  parameters:
    capacity: 12
- type: nvidia::gxf::DownstreamReceptiveSchedulingTerm
  parameters:
    transmitter: data_transmitter
    min_size: 1
- name: allocator
  type: nvidia::gxf::BlockMemoryPool
  parameters:
    storage_type: 1
    block_size: 6266880
    num_blocks: 40
- name: normalizer_operator
  type: nvidia::isaac::tensor_ops::Normalize
  parameters:
    scales: [ 0.0156862745, 0.00490196078, 0.00784313725 ]
    offsets: [ -127.5, -153.0, -63.75 ]
    receiver: data_receiver
    transmitter: data_transmitter
    pool: allocator
    input_adapter: global/adapter_video_buffer
    output_adapter: global/adapter_rgb_f32
    output_name: "image"
---
name: interleaved_to_planar
components:
- name: data_receiver
  type: nvidia::gxf::DoubleBufferReceiver
  parameters:
    capacity: 12
- type: nvidia::gxf::MessageAvailableSchedulingTerm
  parameters:
    receiver: data_receiver
    min_size: 1
- name: data_transmitter
  type: nvidia::gxf::DoubleBufferTransmitter
  parameters:
    capacity: 12
- type: nvidia::gxf::DownstreamReceptiveSchedulingTerm
  parameters:
    transmitter: data_transmitter
    min_size: 1
- name: allocator
  type: nvidia::gxf::BlockMemoryPool
  parameters:
    storage_type: 1
    block_size: 6266880
    num_blocks: 40
- name: interleaved_to_planar_operator
  type: nvidia::isaac::tensor_ops::InterleavedToPlanar
  parameters:
    receiver: data_receiver
    transmitter: data_transmitter
    pool: allocator
    input_adapter: global/adapter_rgb_f32  # nhwc
    output_adapter: global/adapter_planar_rgb_f32  # nchw
    output_name: "input_tensor"
---
name: reshaper
components:
- name: data_receiver
  type: nvidia::gxf::DoubleBufferReceiver
  parameters:
    capacity: 12
- type: nvidia::gxf::MessageAvailableSchedulingTerm
  parameters:
    receiver: data_receiver
    min_size: 1
- name: data_transmitter
  type: nvidia::gxf::DoubleBufferTransmitter
  parameters:
    capacity: 12
- type: nvidia::gxf::DownstreamReceptiveSchedulingTerm
  parameters:
    transmitter: data_transmitter
    min_size: 1
- name: allocator
  type: nvidia::gxf::BlockMemoryPool
  parameters:
    storage_type: 1
    block_size: 6266880
    num_blocks: 40
- type: nvidia::gxf::MemoryAvailableSchedulingTerm
  parameters:
    allocator: allocator
    min_blocks: 1
- name: reshape_operator
  type: nvidia::isaac::tensor_ops::Reshape
  parameters:
    receiver: data_receiver
    transmitter: data_transmitter
    pool: allocator
    input_adapter: global/adapter_planar_rgb_f32
    output_adapter: global/adapter_planar_rgb_f32
    output_name: "input_tensor"
    output_shape: []
---
name: sink
components:
- name: signal
  type: nvidia::gxf::DoubleBufferReceiver
  parameters:
    capacity: 5
- type: nvidia::gxf::MessageAvailableSchedulingTerm
  parameters:
    receiver: signal
    min_size: 1
- name: sink
  type: nvidia::isaac_ros::MessageRelay
  parameters:
    source: signal
---
components:
- name: edge1
  type: nvidia::gxf::Connection
  parameters:
    source: broadcaster/data_transmitter_resizer
    target: resizer/data_receiver
---
components:
- name: edge2
  type: nvidia::gxf::Connection
  parameters:
    source: bbox/data_transmitter
    target: crop_and_resizer/bbox_receiver
---
components:
- name: edge3
  type: nvidia::gxf::Connection
  parameters:
    source: resizer/data_transmitter
    target: crop_and_resizer/data_receiver
---
components:
- name: edge4
  type: nvidia::gxf::Connection
  parameters:
    source: crop_and_resizer/data_transmitter
    target: color_space_converter/data_receiver
---
components:
- name: edge5
  type: nvidia::gxf::Connection
  parameters:
    source: color_space_converter/data_transmitter
    target: normalizer/data_receiver
---
components:
- name: edge6
  type: nvidia::gxf::Connection
  parameters:
    source: normalizer/data_transmitter
    target: interleaved_to_planar/data_receiver
---
components:
- name: edge7
  type: nvidia::gxf::Connection
  parameters:
    source: interleaved_to_planar/data_transmitter
    target: reshaper/data_receiver
---
components:
- name: edge8
  type: nvidia::gxf::Connection
  parameters:
    source: reshaper/data_transmitter
    target: sink/signal
---
components:
- type: nvidia::gxf::EventBasedScheduler
  parameters:
    clock: clock
    stop_on_deadlock: false
    worker_thread_number: 2
- name: clock
  type: nvidia::gxf::RealtimeClock
